
from_to = {
    'basic': {
        'regular': 6,
        'fast': 4,
        'strong': 2,
        'heli': 0,
        'jet': 0,
        'armored': 1,
        'healer': 1,
        'toxic': 6,
        'icy': 2,
        'fighter': 1,
        'light': 4,
        'boss': 4,
        },
    'sniper': {
        'regular': 4,
        'fast': 1,
        'strong': 6,
        'heli': 0,
        'jet': 0,
        'armored': 4,
        'healer': 4,
        'toxic': 2,
        'icy': 1,
        'fighter': 6,
        'light': 1,
        'boss': 4,
        },
    'cannon': {
        'regular': 4,
        'fast': 6,
        'strong': 1,
        'heli': 0,
        'jet': 0,
        'armored': 2,
        'healer': 4,
        'toxic': 4,
        'icy': 6,
        'fighter': 2,
        'light': 2,
        'boss': 4,
        },
    'freezing': {
        'regular': 4,
        'fast': 4,
        'strong': 4,
        'heli': 4,
        'jet': 0,
        'armored': 2,
        'healer': 4,
        'toxic': 4,
        'icy': 0,
        'fighter': 4,
        'light': 4,
        'boss': 4,
        },
    'venom': {
        'regular': 4,
        'fast': 6,
        'strong': 4,
        'heli': 0,
        'jet': 0,
        'armored': 6,
        'healer': 4,
        'toxic': 0,
        'icy': 2,
        'fighter': 2,
        'light': 4,
        'boss': 4,
        },
    'splash': {
        'regular': 1,
        'fast': 4,
        'strong': 2,
        'heli': 2,
        'jet': 2,
        'armored': 1,
        'healer': 2,
        'toxic': 6,
        'icy': 6,
        'fighter': 6,
        'light': 4,
        'boss': 4,
        },
    'blast': {
        'regular': 2,
        'fast': 2,
        'strong': 1,
        'heli': 0,
        'jet': 0,
        'armored': 6,
        'healer': 2,
        'toxic': 1,
        'icy': 1,
        'fighter': 2,
        'light': 1,
        'boss': 4,
        },
    'multishot': {
        'regular': 4,
        'fast': 6,
        'strong': 1,
        'heli': 1,
        'jet': 2,
        'armored': 1,
        'healer': 1,
        'toxic': 4,
        'icy': 4,
        'fighter': 2,
        'light': 6,
        'boss': 4,
        },
    'minigun': {
        'regular': 4,
        'fast': 2,
        'strong': 2,
        'heli': 4,
        'jet': 2,
        'armored': 6,
        'healer': 6,
        'toxic': 2,
        'icy': 1,
        'fighter': 1,
        'light': 1,
        'boss': 4,
        },
    'antiair': {
        'regular': 0,
        'fast': 0,
        'strong': 0,
        'heli': 6,
        'jet': 4,
        'armored': 0,
        'healer': 0,
        'toxic': 0,
        'icy': 0,
        'fighter': 0,
        'light': 0,
        'boss': 0,
        },
    'tesla': {
        'regular': 4,
        'fast': 1,
        'strong': 6,
        'heli': 2,
        'jet': 6,
        'armored': 0,
        'healer': 4,
        'toxic': 4,
        'icy': 1,
        'fighter': 1,
        'light': 2,
        'boss': 4,
        },
    'missile': {
        'regular': 1,
        'fast': 1,
        'strong': 4,
        'heli': 4,
        'jet': 1,
        'armored': 2,
        'healer': 4,
        'toxic': 2,
        'icy': 6,
        'fighter': 2,
        'light': 6,
        'boss': 4,
        },
    'flamethrower': {
        'regular': 4,
        'fast': 4,
        'strong': 2,
        'heli': 0,
        'jet': 0,
        'armored': 1,
        'healer': 0,
        'toxic': 6,
        'icy': 6,
        'fighter': 6,
        'light': 4,
        'boss': 4,
        },
    'laser': {
        'regular': 1,
        'fast': 4,
        'strong': 4,
        'heli': 2,
        'jet': 6,
        'armored': 4,
        'healer': 6,
        'toxic': 2,
        'icy': 1,
        'fighter': 4,
        'light': 1,
        'boss': 4,
        },    
}

to_from = {}

for tower in from_to:
    for monster in from_to[tower]:
        if not monster in to_from:
            to_from[monster] = {}
        to_from[monster][tower] = from_to[tower][monster]